    //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual changes to this file may be lost if the code is regenerated.
// </auto-generated>
namespace AMAY_QUEVEDO_ZAMORA_PROJECT
{
    public partial class signin
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// txtUsername control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtUsername;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// rbStudent control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbStudent;

        /// <summary>
        /// rbAdmin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RadioButton rbAdmin;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// btnSignUp control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSignUp;
    }
}
