# Build workflow for ASP.NET Web Forms (.NET Framework 4.7.2)

name: .NET Framework Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore AMAY_QUEVEDO_ZAMORA_PROJECT/AMAY_QUEVEDO_ZAMORA_PROJECT/AMAY_QUEVEDO_ZAMORA_PROJECT.csproj -PackagesDirectory AMAY_QUEVEDO_ZAMORA_PROJECT/packages

    - name: Build with MSBuild
      run: msbuild AMAY_QUEVEDO_ZAMORA_PROJECT/AMAY_QUEVEDO_ZAMORA_PROJECT/AMAY_QUEVEDO_ZAMORA_PROJECT.csproj /p:Configuration=Release /p:DeployOnBuild=false
